ALTER TABLE "Story"
ADD COLUMN IF NOT EXISTS "firstAction" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "objective" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Session"
ADD COLUMN IF NOT EXISTS "storyFirstAction" TEXT,
ADD COLUMN IF NOT EXISTS "storyObjective" TEXT;
